name = "closelook-chatbot"
type = "theme"
uid = "1a153621-0cb6-3fa7-62a0-276f2ec68d3479891f7d"

[app_bridge]
handle = "closelook-chatbot"

[extension_points]
# App embed that appears in theme customizer under "App embeds"
product_page = ["theme-app-extension/closelook-chatbot-embed.liquid"]
