# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "95615e8665f0cb731eab0dbd66b69ebd"
name = "Closelook Virtual Try-On"
application_url = "https://vton-1-hqmc.onrender.com"
embedded = true

[webhooks]
api_version = "2025-01"
uninstall_url = "https://vton-1-hqmc.onrender.com/api/shopify/webhooks/app-uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,read_content,read_orders,read_customers,write_customers"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://vton-1-hqmc.onrender.com/api/shopify/auth/oauth"
]

[pos]
embedded = false

[app_proxy]
url = "https://vton-1-hqmc.onrender.com"
subpath = "apps"
prefix = "closelook"
